---
title: "Data Processing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(tidyverse)
library(spdep)
library(leaflet)
```

```{r tidy hazard assessment data, warning =F, message =F, error=F}
## Read in file
haz_dat = st_read("../wireframe/data/hazard/WHA2015.shp")
## Transform coordinates to 4326
haz_dat <- st_transform(haz_dat, 4326)
## Make a tidy dataset
tidy_haz <- haz_dat %>% 
  ## converts to mutatable dataframe
  as.data.frame %>%
  ## Removes geometry (too large)
  select(-c(geometry)) %>%
  ## Brings data from wide to long format using key-value pair
  gather(key = hazard, 
         value = score,
         ## Removes all these variables within -c()
         -c(AreaName, Island, AREA, PERIMETER,
            Acres, CAR_Rating, zone, 
            CAR_Hawaii, CAR_adjtot)) %>%
  mutate(
    ## Create new variable for hazard category
    hazard_category = 
    case_when(
    hazard %in% c("Wat_Avail", "Rspn_Time", "Prox_Stn",
                  "FD_Trng", "Wild_Cap", "IntAgCoop",
                  "Loc_Ops", "Com_Plan", "Com_FirPrg") ~ "Fire Protection",
    hazard %in% c("Ing_Eg", "Rd_Maint","Rd_Width",
                  "Rd_Cond", "Fire_Acc", "St_Sign",
                  "Strc_Den", "Hm_Set", "Un_Lands",
                  "Priv_Act", "Prox_Wild") ~ "Subdivision",
    hazard %in% c("Veg_Type", "Fuel_Load", "Fuel_Strc",
                  "Def_Space", "Prox_Flam") ~ "Vegetation",
    hazard %in% c("Roof_Asmb", "Sid_Sof", "Undr_Skrt",
                  "Utlty_Plmt", "Strc_Ign") ~ "Building",
    hazard %in% c("Slope", "Avg_Rain", "Prev_Wind",
                  "Seas_Haz", "Ign_Risk", "Top_Adv") ~ "Fire Environment"
  ))%>%
  mutate(
    ### Create new variable for Assessment reason
    reason =
      case_when(
        ## Subdivision scores
        hazard == "Ing_Eg" & score == 1 ~ "Multiple entrances and exits are well equipped for fire trucks with turnarounds",
        hazard == "Ing_Eg" & score == 2 ~ "Limited access routes. 2 ways in and 2 ways out. Moderate grades",
        hazard == "Ing_Eg" & score == 3 ~ "Narrow, dead end roads or 1 way in, 1 way out. Steep grades",
        hazard == "Rd_Maint" & score == 1 ~ "Wide loop roads that are maintained, paved or solid surface with shoulders",
        hazard == "Rd_Maint" & score == 2 ~ "Roads maintained. Some narrow two lane roads with no shoulders",
        hazard == "Rd_Maint" & score == 3 ~ "Narrow and or single lane, minimally maintained, no shoulders",
        hazard == "Rd_Width" & score == 1 ~ "24’+ wide.Wide roads with drivable shoulders and good visibility allow two-way traffic. Streets in the downtown area are the widest streets in town. Interior streets are smaller and are easily blocked by parked vehicles.",
        hazard == "Rd_Width" & score == 2 ~ "20’-24’ wide. Medium width roads with drivable shoulders and good visibility, support evacuation and emergency response time.",
        hazard == "Rd_Width" & score == 3 ~ "Less than 20 feet wide. Narrow roads coupled with poor visibility limit evacuation and emergency response. Traffic problems will occur. Entrapment is likely.",
        hazard == "Rd_Cond" & score == 1 ~ "Flat or gently sloping surfaced roads can support high volumes of large fire equipment.",
        hazard == "Rd_Cond" & score == 2 ~ "Surfaced road with 5%+ grade or non-surfaced road with <5% grade that can still support fire equipment.  Road and right-of-way maintenances is essential for access and visibility.",
        hazard == "Rd_Cond" & score == 3 ~ "Narrow, steep, or non- surfaced roads are difficult to access. One-way traffic is a hazard. Overhanging brush may damage fire equipment.  Jeep trails and seasonal roads limit 2wd emergency response equipment.",
        hazard == "Fire_Acc" & score == 1 ~ "Adequate turnaround space is available for large fire equipment.",
        hazard == "Fire_Acc" & score == 2 ~ "<300’ with no turnaround. Short or dead-end streets will become crowded with homeowner’s vehicles.",
        hazard == "Fire_Acc" & score == 3 ~ "300’+ with no turnaround. Long dead-end streets will become crowded with vehicles. Two-way visibility is an issue.",
        hazard == "St_Sign" & score == 1 ~ "Present. Most are at least 4’ in size and are reflectorized.",
        hazard == "St_Sign" & score == 2 ~ "Present and reflectorized with some exceptions.",
        hazard == "St_Sign" & score == 3 ~ "Not present.",
        hazard == "Strc_Den" & score == 1 ~ "Low structure density and low ignition probability.",
        hazard == "Strc_Den" & score == 2 ~ "Density and ignition probability are both moderate, or one is high but is balanced by the other being low.",
        hazard == "Strc_Den" & score == 3 ~ "Dense structures with high ignition probability.",
        hazard == "Hm_Set" & score == 1 ~ "Majority (50%+) of homes are set back from property lines and slopes by at least 30 feet.",
        hazard == "Hm_Set" & score == 2 ~ "10-50% of homes have defensible setbacks from property lines and sloped areas.",
        hazard == "Hm_Set" & score == 3 ~ "<10% of homes have defensible setbacks from property lines. Buildings located close to dangerous topographic features such as the tops of slopes.",
        hazard == "Un_Lands" & score == 1 ~ "Few to no weedy vacant lots. Few to no undeveloped unmaintained vegetated areas or corridors between homes.  Less than 10% of lots remain undeveloped and pose an additional wildfire hazard due to lack of maintenance and/or restricted access.",
        hazard == "Un_Lands" & score == 2 ~ "Some isolated unmaintained lots or undeveloped vegetated areas within subdivision.  10-50% of lots have not been developed and pose an additional wildfire hazard due to lack of maintenance and/or restricted access. Hazard ranking is dependent on ignition risk, size of area, and fuel type.",
        hazard == "Un_Lands" & score == 3 ~ "Abundant unmanaged, vegetated corridors and vacant lots throughout community.  Agricultural lands irregularly maintained leaving dry weedy species causing increased ignition risk.  Numerous ladder fuels and high risk fuels. Greater than 75% of lots have not been developed or Separation of adjacent structures that can contribute to fire spread",
        hazard == "Priv_Act" & score == 1 ~ "70% of homes have improved survivable space around property, reduced ignition risk, hardened homes, and no ladder fuels.",
        hazard == "Priv_Act" & score == 2 ~ "30-70% homes have improved survivable space around property and well-maintained landscapes.",
        hazard == "Priv_Act" & score == 3 ~ "<30% of homes have defensible space, hardened home features, or Firewise landscaping.",
        hazard == "Prox_Wild" & score == 1 ~ "Wildland areas share no borders with the subdivision.  Little to no undeveloped and unmaintained vegetated areas within community. Little to no ladder fuels along community boundaries.",
        hazard == "Prox_Wild" & score == 2 ~ "Wildland areas adjoin subdivision on 1-2 sides.",
        hazard == "Prox_Wild" & score == 3 ~ "Wildland areas surround subdivision on at least 3 sides.",
        ## Vegetation
        hazard == "Prox_Flam" & score == 1 ~ "Greater than 100 ft",
        hazard == "Prox_Flam" & score == 2 ~ "40-100 ft",
        hazard == "Prox_Flam" & score == 3 ~ "Less than 40 ft",
        hazard == "Veg_Type" & score == 1 ~ "Grasses less than 6 inches in height. Light leaf litter.",
        hazard == "Veg_Type" & score == 2 ~ "Grasses 6–12 inches in height.  Grasses 6-12” tall. Light brush and small trees.  Patchy fuels.",
        hazard == "Veg_Type" & score == 3 ~ "Dense grass, brush, timber, and/or hardwoods. Moderate to heavy dead and downed vegetation. Fuels greater than 12 feet tall.  Heavy vegetation.",
        hazard == "Fuel_Load" & score == 1 ~ "0-30% cover",
        hazard == "Fuel_Load" & score == 2 ~ "31-70% cover",
        hazard == "Fuel_Load" & score == 3 ~ "71-100% cover",
        hazard == "Fuel_Strc" & score == 1 ~ "Non-contiguous or patchwork arrangement. Little to no ladder fuels.",
        hazard == "Fuel_Strc" & score == 2 ~ "",
        hazard == "Fuel_Strc" & score == 3 ~ "Uninterrupted vegetation, pervasive ladder fuels.",
        hazard == "Def_Space" & score == 1 ~ "Vegetation is treated 100 feet or more from structures.",
        hazard == "Def_Space" & score == 2 ~ "31-100 ft of vegetation treatment from structures.",
        hazard == "Def_Space" & score == 3 ~ "Less than 30 ft of vegetation treatment from structures.",
        ## Building
        hazard == "Roof_Asmb" & score == 1 ~ "Greater than 75% of homes have Class A roofs (metal, asphalt, or fiberglass roofing material).",
        hazard == "Roof_Asmb" & score == 2 ~ "50-75% have Class A roofing.",
        hazard == "Roof_Asmb" & score == 3 ~ "Less than 50% of homes have Class A roofing.",
        hazard == "Sid_Sof" & score == 1 ~ "Greater than 75% of homes have fire resistant siding and soffits.",
        hazard == "Sid_Sof" & score == 2 ~ "50-75% of homes have fire resistant siding and soffits.",
        hazard == "Sid_Sof" & score == 3 ~ "Less than 50% of homes have fire resistant siding and soffits.",
        hazard == "Undr_Skrt" & score == 1 ~ "Greater than 75% of homes have the equivalent of fine non- combustible mesh screening to protect underneath from flying embers and ignition",
        hazard == "Undr_Skrt" & score == 2 ~ "50-75% of homes have the equivalent of fine non-combustible mesh screening",
        hazard == "Undr_Skrt" & score == 3 ~ "Less than 50% of homes have the equivalent of fine non- combustible mesh screening",
        hazard == "Utlty_Plmt" & score == 1 ~ "All underground or none.",
        hazard == "Utlty_Plmt" & score == 2 ~ "One underground, one above ground.",
        hazard == "Utlty_Plmt" & score == 3 ~ "Both above ground.",
        hazard == "Strc_Ign" & score == 1 ~ "Greater than 75% or houses are spaced with cleared boundaries. Flammables and combustible materials stored according to fire-safe principles.",
        hazard == "Strc_Ign" & score == 2 ~ "50-75% of homes store combustibles properly.",
        hazard == "Strc_Ign" & score == 3 ~ "Less than 50% of homes store combustibles properly. Houses close to each other.",
        ## Fire Environment
        hazard == "Slope" & score == 1 ~ "Flat to slight slope (10%)",
        hazard == "Slope" & score == 2 ~ "Moderate slopes (10-30%)",
        hazard == "Slope" & score == 3 ~ "Steep slopes (>30%)",
        hazard == "Avg_Rain" & (score == 1 | score == 2) ~ "High precipitation",
        hazard == "Avg_Rain" & (score == 3 | score == 4) ~ "Moderate precipitation",
        hazard == "Avg_Rain" & (score == 5 | score == 6) ~ "Low precipitation",
        hazard == "Prev_Wind" & score == 1 ~ "Wind rarely (less than 10% of time) exceeds 15 mph. Protection from predominant winds.",
        hazard == "Prev_Wind" & score == 2 ~ "Wind rarely (less than 10% of time) exceeds 15 mph.",
        hazard == "Prev_Wind" & score == 3 ~ "Wind frequently (50% or more of time) exceeds 15 mph or frequent exposure to predominant winds or transitional/converging wind directions.",
        hazard == "Seas_Haz" & score == 1 ~ "Area has no major seasonal increase of fire hazard.",
        hazard == "Seas_Haz" & score == 2 ~ "Area is occasionally (e.g.,once per decade) exposed to fire prone conditions: drought, lightning storms,	desiccated vegetation,and/or strong dry winds.",
        hazard == "Seas_Haz" & score == 3 ~ "Area is seasonally exposed to unusually severe fire weather, drought conditions,	lightning storms, desiccated vegetation, and/or strong dry winds.",
        hazard == "Ign_Risk" & score == 1 ~ "Little to no natural (lightning or lava) ignition risk.  No history of arson. Wildland areas absent or distant from public and/or vehicular access.",
        hazard == "Ign_Risk" & score == 2 ~ "Some history of wildfire, but not particularly fire prone area due to prevailing lack of fire prone conditions, weather, and vegetation type.",
        hazard == "Ign_Risk" & score == 3 ~ "Most historic wildfire events were anthropogenic with easy access to wildland areas via roads or proximity to development OR natural ignition sources such as lightning or lava are prevalent. Fire prone area.  High rate of ignitions or history of large scale fires and/or severe wildfire events.",
        hazard == "Top_Adv" & score == 1 ~ "None.",
        hazard == "Top_Adv" & score == 2 ~ "",
        hazard == "Top_Adv" & score == 3 ~ "Major feature such as box canyon, ravines, chutes, saddles, transition zones.",
        ## Fire Protection
        hazard == "Wat_Avail" & score == 1 ~ "Pressurized water source availability. 500 GPM less than 1000 ft spacing.",
        hazard == "Wat_Avail" & score == 2 ~ "Non-pressurized water source availability (offsite or draft location) or dipsite. Homes on catchment water have fire-hose hookups.",
        hazard == "Wat_Avail" & score == 3 ~ "Water unavailable, or offsite water more than 20 minute roundtrip",
        hazard == "Rspn_Time" & score == 1 ~ "Within 15 minutes",
        hazard == "Rspn_Time" & score == 2 ~ "16-30 minutes",
        hazard == "Rspn_Time" & score == 3 ~ "Greater than 30 minutes",
        hazard == "Prox_Stn" & score == 1 ~ "Less than 5 miles",
        hazard == "Prox_Stn" & score == 2 ~ "6-10 miles",
        hazard == "Prox_Stn" & score == 3 ~ "More than 10 miles",
        hazard == "FD_Trng" & score == 1 ~ "Large fully paid fire department with personnel that meet NFPA or NWCG training requirements and have adequate equipment.",
        hazard == "FD_Trng" & score == 2 ~ "Mixed fire department. Some paid and some volunteer personnel.  Limited experience, training, and equipment to fight fire.",
        hazard == "FD_Trng" & score == 3 ~ "Small, all volunteer fire department.  Limited training, experience, and budget with regular turnover of personnel.  Do not meet NFPA or NWCG standards.",
        hazard == "Wild_Cap" & score == 1 ~ "Sufficient personnel, equipment, and wildland firefighting capability and experience. Good supply of structural and wildland fire apparatus and misc specialty equipment",
        hazard == "Wild_Cap" & score == 2 ~ "Limited personnel, and or equipment but with some wildland firefighting expertise and training. Smaller supply of fire apparatus in fairly good repair with some specialty equipment.",
        hazard == "Wild_Cap" & score == 3 ~ "Fire department non-existent or untrained/unequipped to fight wildland fire. Minimum amount of fire apparatus, which is old and in need of repair. None or little specialty equipment.",
        hazard == "IntAgCoop" & score == 1 ~ "Mutual aid agreements and resources available to deploy.",
        hazard == "IntAgCoop" & score == 2 ~ "Mutual aid agreements but limited resource availability.",
        hazard == "IntAgCoop" & score == 3 ~ "No mutual aid agreements.",
        hazard == "Loc_Ops" & score == 1 ~ "Active EOG or CERT. Evacuation plan in place.",
        hazard == "Loc_Ops" & score == 2 ~ "Limited participation in EOG or similar. Have some form of evacuation process.",
        hazard == "Loc_Ops" & score == 3 ~ "EOG or CERT team, etc. organized and active, prepared for evacuation processes",
        hazard == "Com_Plan" & score == 1 ~ "County/local laws, zoning ordinances, and codes require use of fire safe residential and subdivision designs. Fire department actively participates in planning process and enforces ordinances.  Residents are compliant.",
        hazard == "Com_Plan" & score == 2 ~ "Have voluntary ordinances for fire safe practices. Local officials have an understanding of appropriate wildfire mitigation strategies. Fire department has limited input to fire safe planning and development efforts and limited enforcement. Residents are mostly compliant.",
        hazard == "Com_Plan" & score == 3 ~ "No local codes, laws, or ordinances requiring fire safe building or practices. Community standards for fire safe development and protection are marginal or non-existent.  Little to no effort has been made in assessing and applying measures to reduce wildfire impact.  Ordinances are not enforced and/or residents are not compliant.",
        hazard == "Com_FirPrg" & score == 1 ~ "Organized and active groups provide educational materials and programs throughout the community.",
        hazard == "Com_FirPrg" & score == 2 ~ "Limited provision of or interest in educational efforts. Fire Department or local group does some limited prevention and public education.",
        hazard == "Com_FirPrg" & score == 3 ~ "No interest or participation in educational programs. No prevention education by local fire department."
      )
  ) %>%
  mutate(
    ### Create new variable that specifies full hazard name
    hazard_full =
      case_when(
        ## Subdivision scores
        hazard == "Ing_Eg"  ~ "Ingress & Egress",
        hazard == "Rd_Maint" ~ "Road Maintenance",
        hazard == "Rd_Width" ~ "Road Width",
        hazard == "Rd_Cond" ~ "All-season Road Condition",
        hazard == "Fire_Acc" ~ "Fire Service Access",
        hazard == "St_Sign" ~ "Street Signs",
        hazard == "Strc_Den" ~ "Structure Density",
        hazard == "Hm_Set" ~ "Home Setbacks",
        hazard == "Un_Lands" ~ "Unmanaged, Untended, Undeveloped Lands",
        hazard == "Priv_Act" ~ "Private Landowner actions/ Firewise landscaping and defensible space",
        hazard == "Prox_Wild" ~ "Proximity of Subdivision to Wildland Areas",
        ## Vegetation
        hazard == "Prox_Flam" ~ "Proximity of Flammable Fuels around Subdivision",
        hazard == "Veg_Type" ~ "Type of Predominant Vegetation within 300ft of homes",
        hazard == "Fuel_Load" ~ "Fuel Loading",
        hazard == "Fuel_Strc" ~ "Fuel Structure and Arrangement",
        hazard == "Def_Space" ~ "Defensible Space/ Fuels Reduction around Homes & Structures",
        ## Building
        hazard == "Roof_Asmb" ~ "Roofing Assembly",
        hazard == "Sid_Sof" ~ "Siding & Soffits",
        hazard == "Undr_Skrt" ~ "Under-skirting around decks, lanais, post-and-pier structures",
        hazard == "Utlty_Plmt" ~ "Utilities Placement: Gas and Electric",
        hazard == "Strc_Ign" ~ "Structural Ignitability",
        ## Fire Environment
        hazard == "Slope" ~ "Slope",
        hazard == "Avg_Rain" ~ "Average Rainfall",
        hazard == "Prev_Wind" ~ "Prevailing Wind Speeds and Direction",
        hazard == "Seas_Haz" ~ "Seasonal or Periodic High Hazard Conditions",
        hazard == "Ign_Risk" ~ "Ignition Risk",
        hazard == "Top_Adv" ~ "Topographical Features that adversely affect wildland fire behavior",
        ## Fire Protection
        hazard == "Wat_Avail" ~ "Water Source Availability",
        hazard == "Rspn_Time" ~ "Response Time",
        hazard == "Prox_Stn" ~ "Proximity to Fire Station",
        hazard == "FD_Trng" ~ "Fire department structural training and expertise",
        hazard == "Wild_Cap" ~ "Wildland Firefighting Capability of Initial Response Agency",
        hazard == "IntAgCoop" ~ "Interagency Cooperation",
        hazard == "Loc_Ops" ~ "Local Emergency Operations Group or Other Similar Group",
        hazard == "Com_Plan" ~ "Community Planning Practices and Ordinances",
        hazard == "Com_FirPrg" ~ "Community Fire-Safe Efforts and Programs Already in Place"
      )
  )

## Output file ##
write_csv(tidy_haz, "../wireframe/data/tidy_haz.csv")
```

```{r community input data, warning = F, message = F, error = F}
# Load data
comm_input_dat <-
    # this generates the list of files in that folder
    list.files(path = "../data/community_input/",
               pattern="*.csv", 
               full.names = T) %>% 
    # map over read_csv, col_types specifies that each have same column headers
    map_dfr(~read_csv(., col_types = cols(.default = "c"))) 

## Clean data
# Split secondary desc (should be 15 total)
comm_input_dat <- comm_input_dat %>%
    mutate(
      # combines firewise and Firewise
      secondary_desc = tolower(secondary_desc),
      # combines collab and Collab
      key_codes = tolower(key_codes)
           ) %>%
  # Makes three new columns
    separate(secondary_desc, c("sec_desc1", "sec_desc2", "sec_desc3"), ",")

# Remove potentially complicating $ and '
comm_input_dat$sec_desc1<-gsub("\\$", "money", comm_input_dat$sec_desc1)
comm_input_dat$sec_desc1<-gsub("\\'", "", comm_input_dat$sec_desc1)
# Remove all items after - (e.g. to- ll)
comm_input_dat$sec_desc1<-gsub("\\-.*", "", comm_input_dat$sec_desc1)

# Manipulate data
comm_input_dat <- comm_input_dat %>% 
  # Make votes numeric instead of character
  mutate(total_votes = as.numeric(total_votes)) %>%
  # Changes all remaining character variables to factors
  mutate_if(is.character,funs(factor(.))) %>%
  # Changes concerns and recommendations back to characters
  mutate(concern = as.character(concern),
         recommendations = as.character(recommendations))

## Output data
write_csv(comm_input_dat,"../data/comm_input.csv")
```

```{r community hazard scoring, message=F, warning=F, error=F}
## Read in data as xlsx
dat <- readxl::read_xlsx(path = "../data/2014_3_31_Community Hazard Assessment_Key Final_HWMO.xlsx")
## Output data as csv
write_csv(dat, path = "../wireframe/data/hazard_scoring_system.csv")
```
