---
title: "basic"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(tidyverse)
```

`sf` Resources:
<https://ryanpeek.github.io/mapping_in_R/index.html>
<https://edzer.github.io/rstudio_conf/#1>

```{r load hazard assessment data}
# Load data
haz_dat = st_read("../data/WHA Metadata/WHA2015.shp")
# Check coordinate reference system
st_crs(haz_dat)
# Plot
plot(st_geometry(haz_dat), col="white")
# View data
View(haz_dat)
```


```{r load census data}
# Might be possible to load census data this way...
# library(tidycensus) # tidy data format of census data
# library(USAboundaries)

# Load data
census_dat = st_read("data/Census_Tract_All_Data/Census_Tract_All_Data.shp")
# Check coordinate reference system
st_crs(census_dat)
# Plot
plot(st_geometry(census_dat), col="white")
# View data
View(census_dat)
```

```{r load fire history data}
# Load data
fire_dat = st_read("data/Fire History/HI_Wildfires1.shp")
# Check coordinate reference system
st_crs(fire_dat)
# Plot
fire_dat %>%
  filter(Long < -50) %>%
  ggplot() + 
  geom_point(aes(x= Long, y = Lat))
# View data
View(fire_dat)
```

```{r load community input data}
# Load data
comm_input_dat <-
    # this generates the list of files
    list.files(path = "../data/community_input/",
               pattern="*.csv", 
               full.names = T) %>% 
    # map over read_csv, col_types specifies that each have same column headers
    map_dfr(~read_csv(., col_types = cols(.default = "c"))) 
```

```{r clean community input data}
## split secondary desc (should be 15 total)
comm_input_dat <- comm_input_dat %>%
    mutate(
      # combines firewise and Firewise
      secondary_desc = tolower(secondary_desc),
      # combines collab and Collab
      key_codes = tolower(key_codes)
           ) %>%
    separate(secondary_desc, c("sec_desc1", "sec_desc2", "sec_desc3"), ",")

# Remove potentially complicating $ and '
comm_input_dat$sec_desc1<-gsub("\\$", "money", comm_input_dat$sec_desc1)
comm_input_dat$sec_desc1<-gsub("\\'", "", comm_input_dat$sec_desc1)
# Remove all items after - (e.g. to- ll)
comm_input_dat$sec_desc1<-gsub("\\-.*", "", comm_input_dat$sec_desc1)

# Manipulate data
comm_input_dat <- comm_input_dat %>% 
  mutate(total_votes = as.numeric(total_votes)) %>%
  mutate_if(is.character,funs(factor(.))) %>%
  mutate(concern = as.character(concern),
         recommendations = as.character(recommendations))
```









