---
title: "leaflet_port"
author: "VanMcG"
date: "March 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(leaflet)
library(sf)
library(geojsonio)
library(rgdal)
library(htmltools)
library(tidyverse)
library(spdep)
```



```{r}
m <- leaflet() %>%
  addProviderTiles(providers$OpenMapSurfer.Grayscale) %>%
  setView(-156, 20.35, 8) %>% #long, lat, zoom level 
  setMaxBounds(-162.6,23.6,-153.5,18.0) %>% 
  # the two diagonal pts that limit panning (long1, lat1, long2, lat2)
   addEasyButton(easyButton(
    icon="fa-globe", title="Zoom to Level 8",
    onClick=JS("function(btn, map){ map.setZoom(8); }")))

  m
```

## Load test fire layer
```{r}
# fire_dat <- fire_dat
# data(fire_dat)
OFires <- geojsonio::geojson_read("../data/Fire History/Oahu_Wildfires.geojson", what = "sp")
MFires <- geojsonio::geojson_read("../data/Fire History/Maui_Wildfires.geojson", what = "sp")

# Load data
census_dat = st_read("../data/Census_Tract_All_Data/Census_Tract_All_Data.shp")
# Check coordinate reference system
st_crs(census_dat)

# Load data
haz_dat <- geojsonio::geojson_read("../data/WHA Metadata/WHA_zones_choro.geojson", what = "sp")

addPolygons(m, data = census_dat) %>%
addPolygons(data = haz_dat)
```


#Multilayer test
```{r}
palxyz <- colorQuantile(
  palette = "PuBuGn",
  domain = census_dat$MedH_Inc
)
addMarkers(m, lng = ~X, lat = ~Y, data = OFires@data, clusterOptions = markerClusterOptions(), group = "O_fires") %>% 
  addMarkers(lng = -156.54, lat = 21.09, group = "P_test") %>% 
  addPolygons(data = census_dat, color = '#000000', weight = 1,
              fillColor = ~colorQuantile("PuBuGn", n = 5, MedH_Inc) (MedH_Inc),
              highlightOptions = highlightOptions(stroke = "#ff0505", 
                                                  weight = 4.0,
                                                  opacity = 1.0,
                                                  bringToFront = TRUE),
              #popup = ~census_dat$MedH_Inc,
              popup = paste("<b>This is not the right data: </b></br>", census_dat$Homeowner), #for test purposes
              #label and popup only accept things that can be reduced to strings. Ugh.
              #labels and popups can read factors, but choropleths can only read numbers
              #one solution is to have duplicate columns
              group = "M_income"
  ) %>%
  
  
  # addPolygons(data = census_dat, color = '#000000', weight = 1,
  #             fillColor = ~colorQuantile("YlGnBu", n = 5, Homeowner) (Homeowner),
  #             opacity = 1.0,
  #             highlightOptions = highlightOptions(stroke = "#ff0505", 
  #                                                 weight = 4.0,
  #                                                 opacity = 1.0,
  #                                                 bringToFront = TRUE),
  #             popup = "<b>% Homeowner</b>", #for test purposes
  #             group = "H_ownr"
  # ) %>%
  
  addPolygons(data = census_dat, color = '#000000', weight = 1,
              fillColor = ~colorQuantile("Reds", n = 5, NH_ac) (NH_ac),
              opacity = 1.0,
              highlightOptions = highlightOptions(stroke = "#ff0505", 
                                                  weight = 4.0,
                                                  opacity = 1.0,
                                                  bringToFront = TRUE),
              label = census_dat$NAME, #for test purposes
              group = "NH_ac"
  ) %>%
    # addLegend("bottomright", values = ~NH_ac,
    #         colors = "Reds",
    #         group = "NH_ac",
    #        #group as unused argument. Don't understand the error here
    #         opacity = 1,
    #         labels = census_dat$NH_ac
    #       
    #       ) %>%
  
   addPolygons(data = haz_dat, color = '#000000', weight = 1,
              fillColor = ~colorQuantile("YlOrBr", n = 5, haz_dat$FIREPROTOT) (FIREPROTOT),
              opacity = 1.0,
              highlightOptions = highlightOptions(stroke = "#ff0505", 
                                                  weight = 4.0,
                                                  opacity = 1.0,
                                                  bringToFront = TRUE),
              label = haz_dat$AreaName, #for test purposes
              group = "FP_score") %>%
  

  
  #controls
  addLayersControl(
    baseGroups = c("M_income", "FP_score", "NH_ac"),
    overlayGroups = c("O_fires", "P_test"),
    options = layersControlOptions(collapsed = FALSE)
  ) 
  
  # addLegend("bottomright", pal = palxyz, values = census_dat$MedH_Inc,
  #         title = "Med.HH Income ($)",
  #         opacity = 1
  #         )

  

# m <- m %>% leaflet(OFires) %>%
#   addTiles() %>%
#   addMarkers(popup = ~Start_Date, clusterOptions = markerClusterOptions())
# m
```

##Hazdata test
```{r}
  addPolygons(m, data = haz_dat, color = '#000000', weight = 1,
              fillColor = ~colorQuantile("YlOrBr", n = 5, haz_dat$FIREPROTOT) (FIREPROTOT),
              opacity = 1.0,
              highlightOptions = highlightOptions(stroke = "#ff0505", 
                                                  weight = 4.0,
                                                  opacity = 1.0,
                                                  bringToFront = TRUE),
              label = haz_dat$AreaName, #for test purposes
              group = "H_score"
  ) 
```

## Load tile layer
```{r}
# fire_dat <- fire_dat
# data(fire_dat)
OFires <- geojsonio::geojson_read("../data/Fire History/Oahu_Wildfires.geojson", what = "sp")

leaflet(OFires) %>%
  addTiles() %>%
  addMarkers()
```

## Add layer control
```{js}
var ptMaps = {
  "Maui Fires": fires_M,
  "Oahu Fires": fires_O
};
var choroMaps = {
  "WHA Fire Quintiles": WHA,
  "Haz Assessment": WHA_hz
};

L.control.layers(choroMaps, ptMaps).addTo(map);
```

```{r}
map <-- leaflet() %>%
  addLayersControl(
    overlayGroups = c(""),
    baseGroups = c(""),
    options = layersControlOptions( collapsed = FALSE)
  )
```

## THE WHOLE THING
```{r}
m <- leaflet(OFires) %>%
  # initialize the map, set boundaries
  setView(-156, 20.35, 8) %>% #long, lat, zoom level 
  setMaxBounds(-162.6,23.6,-153.5,18.0) %>% 
     # the two diagonal pts that limit panning (long1, lat1, long2, lat2)
 addEasyButton(easyButton(
    icon="fa-globe", title="Zoom to Level 8",
    onClick=JS("function(btn, map){ map.setZoom(8); }"))) %>%
  
  #Map tiles
  addProviderTiles(providers$OpenMapSurfer.Grayscale, group = "Roads") %>%
  #addProviderTiles(providers$OpenTopoMap, group = "Topo") %>%
  
  #Base groups (polygons)
  
  #Overlay groups (points)
  addMarkers(popup = ~Start_Date, clusterOptions = markerClusterOptions())
  
  m
```

## load point layers
```{r}
map
```

## clustering?
```{r}
map
```

